name: NHTTAC Consultant Applications Block
type: module
description: NHTTAC Consultant Applications.
# core: 8.x
dependencies:
  - drupal:block
  - drupal:node

# Information added by Drupal.org packaging script on 2018-09-10
version: '8.x-1.x-dev'
core: '8.x'
project: 'nhttac'
datestamp: 1536620584
